# Generated by Django 3.2.4 on 2021-08-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('contentenido', models.TextField()),
                ('imagen', models.ImageField(upload_to='imagenes')),
            ],
        ),
        migrations.CreateModel(
            name='inicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('contentenido', models.TextField()),
                ('imagen', models.ImageField(upload_to='imagenes')),
                ('fecharegistro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('contentenido', models.TextField()),
                ('imagen', models.ImageField(upload_to='imagenes')),
            ],
        ),
        migrations.CreateModel(
            name='portada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('contentenido', models.TextField()),
                ('imagen', models.ImageField(upload_to='imagenes')),
            ],
        ),
        migrations.CreateModel(
            name='portafolios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('contentenido', models.TextField()),
                ('imagen', models.ImageField(upload_to='imagenes')),
            ],
        ),
    ]
